import { defineConfig } from 'eslint/config'
import tseslint from '@electron-toolkit/eslint-config-ts'
import eslintConfigPrettier from '@electron-toolkit/eslint-config-prettier'
import eslintPluginReact from 'eslint-plugin-react'
import eslintPluginReactHooks from 'eslint-plugin-react-hooks'
import eslintPluginReactRefresh from 'eslint-plugin-react-refresh'

export default defineConfig(
  { ignores: ['**/node_modules', '**/dist', '**/out', '**/coverage'] },
  tseslint.configs.recommended,
  eslintPluginReact.configs.flat.recommended,
  eslintPluginReact.configs.flat['jsx-runtime'],
  {
    settings: {
      react: {
        version: 'detect'
      }
    }
  },
  {
    files: ['**/*.{ts,tsx}'],
    plugins: {
      'react-hooks': eslintPluginReactHooks,
      'react-refresh': eslintPluginReactRefresh
    },
    rules: {
      ...eslintPluginReactHooks.configs.recommended.rules,
      ...eslintPluginReactRefresh.configs.vite.rules
    }
  },
  {
    // shadcn/ui components are generated by the shadcn CLI and kept as generated.
    files: ['src/renderer/src/components/ui/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/explicit-function-return-type': 'off',
      'react-refresh/only-export-components': 'off'
    }
  },
  {
    // src/shared runs in both the main process and the renderer, so it must stay pure TypeScript.
    files: ['src/shared/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: [
                'electron',
                'electron/*',
                '@electron-toolkit/*',
                'react',
                'react/*',
                'react-dom',
                'react-dom/*',
                'node:*',
                'fs',
                'fs/*',
                'path',
                'os',
                'child_process',
                'better-sqlite3',
                '@renderer/*',
                '@tanstack/*',
                'zustand',
                'sonner',
                'lucide-react',
                'radix-ui'
              ],
              message: 'src/shared must stay pure TypeScript, usable by both main and renderer.'
            }
          ]
        }
      ],
      'no-restricted-globals': [
        'error',
        'window',
        'document',
        'navigator',
        'location',
        'localStorage',
        'sessionStorage',
        'indexedDB',
        'fetch',
        'process',
        'Buffer',
        'require',
        '__dirname',
        '__filename',
        'global',
        'globalThis'
      ]
    }
  },
  {
    // Main-process code reaches SQLite only through the Db adapter, so the driver stays swappable.
    files: ['src/main/**/*.ts'],
    ignores: ['src/main/db/adapter.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'better-sqlite3',
              message: 'Use the Db adapter (src/main/db/adapter.ts) instead of the SQLite driver.'
            }
          ]
        }
      ]
    }
  },
  {
    // The renderer is sandboxed web content: it reaches the main process only through window.api.
    files: ['src/renderer/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: [
                'electron',
                'electron/*',
                '@electron-toolkit/*',
                'node:*',
                'fs',
                'fs/*',
                'path',
                'os',
                'child_process',
                'better-sqlite3'
              ],
              message: 'The renderer has no Node.js or Electron access. Use window.api instead.'
            }
          ]
        }
      ]
    }
  },
  eslintConfigPrettier
)
